version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  